"""
Django settings for example_project project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This is just an example project, it is fine to leave this here.
SECRET_KEY = "django-insecure-&9%3k12n*0aub%5=fk29cnrw1=oy0@l6-=fu4b4_n=&^8yd5vq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",
    "dj_redis_panel",
    "dj_cache_panel",
    "dj_celery_panel",
    "example_project",  # For management commands
    "app",  # Example app with test tasks
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "example_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "example_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use environment variables to determine database backend
# Defaults to SQLite for local development
DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite")

if DB_ENGINE == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
            "HOST": os.environ.get(
                "POSTGRES_HOST", "postgres"
            ),  # 'postgres' for Docker, 'localhost' for local
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        },
    }
else:
    # Default to SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DJ_REDIS_PANEL_SETTINGS = {
    "ALLOW_KEY_DELETE": False,
    "ALLOW_KEY_EDIT": False,
    "ALLOW_TTL_UPDATE": False,
    "CURSOR_PAGINATED_SCAN": False,
    "CURSOR_PAGINATED_COLLECTIONS": False,
    "socket_timeout": 5.0,
    "socket_connect_timeout": 5.0,
    "INSTANCES": {
        "local_redis": {
            "description": "Local Redis Instance",
            "host": "redis",
            "port": 6379,
            "features": {
                "ALLOW_KEY_DELETE": True,
                "ALLOW_KEY_EDIT": True,
                "ALLOW_TTL_UPDATE": True,
                "CURSOR_PAGINATED_SCAN": True,
                "CURSOR_PAGINATED_COLLECTIONS": True,
            },
        },
    },
}


#########################
# Celery Configuration #
#########################
# Celery Configuration (using modern Celery 4.x+ naming)
CELERY_BROKER_URL = "redis://redis:6379/0"

CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600,
}

# Store task results in Django database
CELERY_RESULT_BACKEND = "django-db"

# Optional: Track task started state
CELERY_TASK_TRACK_STARTED = True

# Store extended task result metadata (task name, args, kwargs, worker)
CELERY_RESULT_EXTENDED = True

# Timezone for beat schedule
CELERY_TIMEZONE = "UTC"

# Celery Beat Schedule - Periodic Tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Run every 30 seconds (good for testing)
    "send-notification-every-30-seconds": {
        "task": "app.tasks.send_periodic_notification",
        "schedule": 30.0,
    },
    # Run every 5 minutes
    "health-check-every-5-minutes": {
        "task": "app.tasks.health_check",
        "schedule": 300.0,  # 5 minutes in seconds
    },
    # Run every hour at minute 0
    "generate-report-hourly": {
        "task": "app.tasks.generate_hourly_report",
        "schedule": crontab(minute=0),  # Every hour at :00
    },
    # Run daily at midnight
    "cleanup-old-results-daily": {
        "task": "app.tasks.cleanup_old_results",
        "schedule": crontab(hour=0, minute=0),  # Daily at 00:00
    },
}

CELERY_QUEUES = {
    "default": {
        "exchange": "default",
        "exchange_type": "direct",
        "routing_key": "default",
    },
    "email": {
        "exchange": "email",
        "exchange_type": "direct",
        "routing_key": "email",
    },
    "heavy": {
        "exchange": "heavy",
        "exchange_type": "direct",
        "routing_key": "heavy",
    },
    "periodic": {
        "exchange": "periodic",
        "exchange_type": "direct",
        "routing_key": "periodic",
    },
}

#########################
# DJ Celery Panel Configuration
#########################

DJ_CELERY_PANEL_SETTINGS = {
    # Backend classes for each interface
    "tasks_backend": "dj_celery_panel.celery_utils.CeleryTasksDjangoCeleryResultsBackend",
    "worker_backend": "dj_celery_panel.celery_utils.CeleryWorkerListInspectBackend",
    "queue_backend": "dj_celery_panel.celery_utils.CeleryQueueListInspectBackend",
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Simple Console Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        # Django Celery Panel logging
        "dj_celery_panel": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
        # Root logger
        "root": {
            "handlers": ["console"],
            "level": "WARNING",
        },
    },
}
